### PR TITLE
Make sure we read stderr to not end up with a hang when the stderr buffer fills

### PR DESCRIPTION
**Pull request by mmangino**

### CODE REVIEW

**Comment by jyurek** [comment]
NB: This was originally posted as https://github.com/thoughtbot/cocaine/pull/97 and thanks to @mmangino for moving it over.

**Comment by mfo** [comment]
I reached this PR via paperclip (5.3.?) which is impacted. 

This error occured after I upgraded to the last version of image magick (imagemagick: stable 7.0.7-26 (bottled), HEAD). Now image magick returns much more verbose errors which ends up hanging up the process (my case when thumbnailing a corrupted JPEG).

Hope it will land soon in terrapin/paperclip

**Comment by sribalakumar** [comment]
Anytime soon this is expected to be merged. Waiting for this PR as we are stuck on the same problem.

**Comment by elisuh** [comment]
@mmangino Hello! Are you still looking to get this merged? I tried to rebase your branch with main and push it up, but don't have access. Once you rebase with main and CI is good, we can get this merged. Thanks so much for your patience. 😄

**Comment by stuzart** [comment]
this was merged into `master` and not `main`, so the problem still exists in the latest 1.0.1 release

**Comment by leifg** [comment]
PR #40 merges all changes into main

**Pull request merged**
